### ISSUE TITLE
Ddox does not generate links to symbols

### ISSUE THREAD

**Issue by FreeSlave** [rejectedsoftware/ddox#124]
After upgrading to 0.15.2 I noticed that ddox no longer automatically generates links to symbols, e.g. types or function parameters when their names are met in doc comments.

**Comment by s-ludwig** [comment]
This was a change that was planned since a long time to be compatible with Ddoc. Well, in fact it was a side-effect of a bugfix, but was planned anyway. Cross-references are still emitted in code sections, including backtick-inline-code and the `$(D ...)` macro. But if necessary, it would be possible to add a command line option to get the old behavior.

**Comment by MyLittleRobo** [comment]
I think this should be applied automatically in See_Also and Throws sections, because symbols are expected to be references there.

**Comment by s-ludwig** [comment]
I don't know. Usually I'd only list symbols in a "See_Also" section, but as far as I know, the spec says nothing about the contents there. And in "Throws" sections, I personally tend to write prose, so it's not much different from other sections.

**Comment by s-ludwig** [comment]
Going to close this as "won't fix" for now, but if there is need for a command line switch, please let me know.
