### ISSUE TITLE
Backticks not parsed correctly

### ISSUE THREAD

**Issue by CyberShadow** [rejectedsoftware/ddox#80]
See third line in example:

http://dlang.org/library/std/path/glob_match.html

The relevant code is:

```d
assert (globMatch(`foo/foo\bar`, "f*b*r"));
```

**Comment by s-ludwig** [comment]
Already fixed by 38977a9fa2c691b756812dd8760923e5550a634b. We should probably update dpl-docs to use 0.10.8. It also fixes detection of documented unit tests and parsing of storage classes for function parameters.

**Comment by CyberShadow** [comment]
Don't we want the site to always use the latest version of the software?

**Comment by s-ludwig** [comment]
Yes, in theory. But manually sticking to a certain set of dependency versions has the advantage that everyone is on the same page and we can be sure to have a working combination of versions. In the beginning, Andrei had constant troubles in the beginning, because he was using old/different versions when he tried to build the site.

It would take a `${DUB} update --root=${DPL_DOCS_PATH} || true` line in the `dpl-docs` target to always use the latest version.

**Comment by CyberShadow** [comment]
Yes, you're right. If a change breaks the build we need to be able to undo it easily.
