### ISSUE TITLE
Macro for "path to base of docs"?

### ISSUE THREAD

**Issue by Abscissa** [rejectedsoftware/ddox#87]
AFAICT, there doesn't appear to be a macro that provides a relative path to the base directory of the documentation output.

Ie: In file ```someproject/docs_output/my_package/my_module/MyClass.html``` something like ```$(DDOX_BASE)``` would expand to ```../../```.

Ddox does this internally for the auto-generated navigation links, but it would be helpful to have this exposed to documentation authors.

**Comment by s-ludwig** [comment]
I'm a little worried about making this a DDOX feature when Ddoc doesn't have it, as the goal is to have a fully compatible alternative. But any serious DDOX-only feature would potentially lead people to produce Ddoc-incompatible documentation comments. Do you have an example use case? Maybe there is an alternative solution? If not, we can of course add such a macro.

**Comment by aG0aep6G** [comment]
> Do you have an example use case?

On dlang.org, we like to make URLs relative so that they work in the HTML files that are part of the dmd releases. We use a `$(ROOT_DIR)` macro that's set to `..` on the Ddoc pages, but on the DDOX pages we need to set it to `/` (i.e. not relative) because of the nested directories. We could add the correct amount of `../`s directly on the link instances, but that would break the Ddoc pages. A `$(DDOX_BASE)` macro would allow us to have both working at the same time.

**Comment by s-ludwig** [comment]
It seems like the `$(ROOT_DIR)` macro is only used within the .dd files of dlang.org, but not within the embedded documentation on which DDOX is run. Is there any concrete example where this would be useful?

**Comment by Abscissa** [comment]
**Regarding use-case:**

Without ever requiring any configuration, the generated documentation could be copied as-is to any base path location, on any server, or viewed by any user locally, with or without ddox even installed let alone anyone ever needing to run `ddox serve-html` first.

Other options (all inferior):

- *Hardcoding `/`:* Terrible option: Documentation can never be hosted within a subdirectory or viewed locally by end-users with `file:///`, and a server of some sort is always required. The inability to work from a subdirectory places restriction and burden on the server maintainer. It also gets in the way of easily offering hosted docs for prior releases (ex: `example.com/docs/...`, `example.com/docs/v0.9/...`, `example.com/docs/v1.2/...` ). On top of all that, this approach doesn't even offer any real benefit (aside from "'breaking' DDOC", which I address below).

- *Setting up a configurable relative-path `$(ROOT_DIR)`:* Broken by DDOX's nested directory structure. Even if that was changed (which I don't advocate since I like the nested structure), it would still have the same downfall as the next option:

- *Setting up a configurable absolute-path `$(ROOT_DIR)`:* Generated docs are neither relocatable, nor zero-configuration: Every time the docs are to be placed in a different location, or viewed locally by an end-user,  `$(ROOT_DIR)` would need to be re-configured and the docs must be rebuilt. All that for no real benefit (aside from "'breaking' DDOC", which I address below).

**"Breaking" DDOC:**

In short: So what?

1. DDOC is known to be insufficient, that's why things like DDOX exist in the first place. Otherwise, DDOX could have been nothing more than a set of macros and CSS files.

2. Making documentation comments work with multiple doc generating tools isn't a feature, it's an unjustified burden. It forces developers to be limited by a common subset of both the tool they chose AND the tools they chose *against*. And for what? Documentation doesn't need to be generatable with multiple doc generators. There's no benefit: As long as the one they're written for is available to contributors, that's all that's needed. DDOX being backwards-compatible with DDOC is nice, so users can upgrade to DDOX if they've been using the built-in, but after that, helping them do their work is more important than continually holding them back by a tool they've already ditched.

3. ***(Probably the most compelling reason)*** **That ship's already sailed anyway:** Linking across different parts of the documentation, in a way that works for *both* DDOC and DDOX is *already* impossible, at least in the general case. First, DDOX's automatic no-macro links don't happen in DDOC. And secondly, manual linking is broken by DDOC and DDOX using different directory structure. The only ways to fix this would involve making DDOX less of an improvement over DDOC, thus defeating the point of even having DDOX.

**Comment by aG0aep6G** [comment]
> It seems like the $(ROOT_DIR) macro is only used within the .dd files of dlang.org, but not within the embedded documentation on which DDOX is run.

It's used through other macros. Examples:
* [`DDLINK`](https://github.com/D-Programming-Language/dlang.org/blob/c086a3ccf9bf05b19d227bdc5bfc97bcad8ae999/dlang.org.ddoc#L102) is defined in terms of `ROOT_DIR`. It's used in [std.algorithm.iteration](https://github.com/D-Programming-Language/phobos/blob/25aae210491fc64c26ca5b2c10bfac9cd17aa481/std/algorithm/iteration.d#L3900), for example.
* The new [`REF`](https://github.com/D-Programming-Language/dlang.org/blob/c086a3ccf9bf05b19d227bdc5bfc97bcad8ae999/dlang.org.ddoc#L323) macro is defined in terms of [`PHOBOS_PATH`](https://github.com/D-Programming-Language/dlang.org/blob/c086a3ccf9bf05b19d227bdc5bfc97bcad8ae999/dlang.org.ddoc#L181) which builds on `ROOT_DIR`. `REF` is supposed to replace other macros like `XREF`.
* Speaking of [`XREF`](https://github.com/D-Programming-Language/dlang.org/blob/c086a3ccf9bf05b19d227bdc5bfc97bcad8ae999/dlang.org.ddoc#L460), we would have liked to [make it relative](https://github.com/D-Programming-Language/dlang.org/pull/1082), but didn't because of DDOX. `XREF` is ubiquitous.

**Comment by s-ludwig** [comment]
@aG0aep6G: Okay, thanks, I missed those. So `REF` and `XREF` can be implemented much simpler for DDOX, because it will do the cross references automatically. Just have it output the qualified name of the symbol in backticks. But `DDLINK` is indeed an issue. I was thinking about a solution that is local to the overridden `ddox.layout.dt` template, but that doesn't really work. I'll add `$(DDOX_ROOT_DIR)`.
